#!/bin/bash

source "${EPX_HOME}/helpers/colorize.sh"
source "${EPX_HOME}/helpers/colors.sh"

echo -e "[$(_c LIGHT_BLUE "Docker - Help")]"
echo -e "  $(_c CYAN "Commands:")"
echo -e "    $(_c LIGHT_CYAN "d.attach") - Attach to a running container"
echo -e "    $(_c LIGHT_CYAN "d.compose") - Docker Compose commands"
echo -e "    $(_c LIGHT_CYAN "d.exec") - Execute a command in a container"
echo -e "    $(_c LIGHT_CYAN "d.help") - Display this help message"
echo -e "    $(_c LIGHT_CYAN "d.inspect") - Inspect a container or image"
echo -e "    $(_c LIGHT_CYAN "d.list") - List all containers"
echo -e "    $(_c LIGHT_CYAN "d.logs") - View logs of a container"
echo -e "    $(_c LIGHT_CYAN "d.make") - Build images or containers"
echo -e "    $(_c LIGHT_CYAN "d.network") - Manage Docker networks"
echo -e "    $(_c LIGHT_CYAN "d.prune") - Prune unused Docker objects"
echo -e "    $(_c LIGHT_CYAN "d.remove") - Remove containers or images"
echo -e "    $(_c LIGHT_CYAN "d.restart") - Restart a container"
echo -e "    $(_c LIGHT_CYAN "d.shell") - Open a shell in a container"
echo -e "    $(_c LIGHT_CYAN "d.start") - Start a container"
echo -e "    $(_c LIGHT_CYAN "d.stats") - Display stats of a container"
echo -e "    $(_c LIGHT_CYAN "d.stop") - Stop a container"
echo -e "    $(_c LIGHT_CYAN "d.up") - Start services with Docker Compose"
echo -e "  $(_c CYAN "Aliases:")"
echo -e "    $(_c LIGHT_CYAN "d") - Docker"
echo -e "    $(_c LIGHT_CYAN "dc") - Docker Compose"
